(function(g){var window=this;'use strict';var jnb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},knb=function(a,b){var c=new g.TS;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},lnb=function(a,b){var c,d,e;
return g.H(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.jE(),2);if(3!=f.j){d=f.B;if(!d)throw g.ND("gct");return g.z(f,g.hT(d),3)}e=f.B;return f.return(e.get("captions",c))})},mnb=function(a,b,c){lnb(a,b).then(function(d){d&&c(d.trackData,new g.TS(d.metadata))})},pnb=function(a){if(!nnb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(onb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},qnb=function(){return g.kD("yt-player-caption-display-settings")},G4=function(){this.segments=[]},rnb=function(a,b){var c=g.Wb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Ib(a.segments,c),g.Ib(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Sb(a.segments,c,0,b),g.Sb(a.segments,c+1,0,b)))},snb=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.ma=c;this.Z=d;this.G=e;this.W=f;this.D=new G4;this.K=-1;this.C=this.B=this.j=null;this.N=new g.ev(this.iY,1E3,this);this.events=new g.hL(this);g.M(this,this.N);g.M(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.vA);this.vA();this.iY()},tnb=function(a){return a.j&&a.j.C?a.j.C+a.player.Qc()<a.player.getCurrentTime():!1},unb=function(a,b){var c=g.VNa(b,a.policy,{}).Oe(),d={format:"RAW",
withCredentials:!0};if(a.policy.Ba){d.method="POST";var e=b.D,f=(0,g.PZ)([120,0]);e&&g.eP(e,g.nWa);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.vC(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.B){var l=!(a.G?h.response:h.responseText)||400<=h.status,m=g.KOa(h);if(m){h=g.VNa(a.B,a.policy,{});a.B.Pk(h,m);unb(a,a.B);break a}l?a.player.va("capfail",{status:h.status}):(a.player.wi().Mi("fcb_r"),m=a.B.eb[0].Pa,null!=a.Z&&a.K!==m&&(l=a.B.eb[0],a.G?a.Z(h.response,1E3*(l.startTime+a.player.Qc())):
a.Z(h.responseText,1E3*(l.startTime+a.player.Qc())),a.K=m))}a.B=null;a.C=null}}).xl(function(h){a.B=null;
a.C=null;var l;a.player.va("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.B=b;rnb(a.D,a.B.eb[0].Pa)},H4=function(a,b){g.aW.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.G=!1;this.K=g.XJ(this.J.U())&&!this.j.isManifestless},wnb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.PWa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.hlb.get(e);null==q&&(q=vnb[e]||vnb[e.replace(/-/g,"_")],g.hlb.set(e,q));h=q||h}c.push(new g.TS({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
xnb=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},ynb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.PWa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},znb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in g.vlb?g.vlb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={XD:c.XD};c.XD=d;var e=function(f){return function(){return String(a[f.XD])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.XD+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.XD,"gi"),e)}return b},I4=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Ve);a.params.Ve&&Object.assign(r,a.params.Ve);Object.assign(r,c.Ve);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Ve=r;var t=1===q.Li,v=[{I:"span",S:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],x,B,E;(l=l.kb("caption_edit_on_hover")&&(null==(x=n.getVideoData().getPlayerResponse())?void 0:null==(B=x.captions)?void 0:null==(E=B.playerCaptionsTracklistRenderer)?void 0:E.openTranscriptCommand))&&
v.unshift({I:"button",S:"caption-edit",Y:{tabindex:"0","aria-label":znb()},V:[{I:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.V.call(this,{I:"div",S:"caption-window",Y:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:v});var F=
this;this.K=[];this.Ga=!1;this.B=a;this.Na=this.Ka=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=.96*f;this.maxHeight=.96*h;this.j=q;this.Nc=c;this.ra=b;this.D=this.Ha("captions-text");this.Wb=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.Ua=Anb(d,e,f,h);this.Jc=m;l&&(this.G=this.Ha("caption-edit"),this.T(this.G,"click",function(){F.Jc()}));
this.type=0;this.fb=this.Ua*Bnb(r);this.Db=p;a=new g.xV(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.U1,this);a.subscribe("dragmove",this.T1,this);a.subscribe("dragend",this.S1,this);this.jb=this.Za=this.ub=this.qb=0;a="";this.j.windowOpacity&&(a=pnb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":Cnb[this.j.textAlign]};this.Wb&&(b["border-radius"]=a?this.fb/8+"px":"");(this.C=
2===this.B.params.Li||3===this.B.params.Li)&&Dnb(this,this.element);g.us(this.element,b);if(p){var G;null==(G=this.element.parentElement)||G.style.setProperty("--caption-window-color",a)}switch(this.j.Ol){case 0:case 1:case 2:g.mv(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.mv(this.element,"ytp-caption-window-bottom")}},Dnb=function(a,b){var c="vertical-rl";
1===a.j.VR&&(c="vertical-lr");g.mf&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.us(b,"-o-writing-mode",c);g.us(b,"-webkit-writing-mode",c);g.us(b,"writing-mode",c);g.us(b,"text-orientation","upright");g.mv(b,"ytp-vertical-caption");3===a.B.params.Li&&(g.us(b,"text-orientation",""),g.us(b,"transform","rotate(180deg)"))},Bnb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Enb=function(a,b){var c={},d=b.background?b.background:a.j.Ve.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Ve.backgroundOpacity;d=pnb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Wb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ua*Bnb(b)+"px";d=1;e=b.color||a.j.Ve.color;if(b.color||null!=b.textOpacity)e=pnb(e),d=null==b.textOpacity?a.j.Ve.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.LM&&(h=e=b.LM);var l=a.Ua/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.FC()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Ve.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.O7&&(c.visibility="hidden");1===b.wX&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.IS||g.MD,3===a.B.params.Li?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.oo||2===b.oo||3===b.oo||4===b.oo||5===b.oo)if(g.IS)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.oo){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},J4=function(a){a=a.split("px");
return 0<a.length?(a=Number(a[0]))?a:0:0},Fnb=function(a){a.N=g.tf("SPAN");
g.us(a.N,{display:"block"});g.mv(a.N,"caption-visual-line");a.D.appendChild(a.N)},Gnb=function(a,b){var c=g.tf("SPAN");
g.us(c,{display:"inline-block","white-space":"pre-wrap"});g.us(c,Enb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.us(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.us(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Hnb=function(a,b,c){a.Ga=a.Ga||!!c;
var d={};Object.assign(d,a.j.Ve);Object.assign(d,c||b.j);Object.assign(d,a.Nc.Ve);(c=!a.N)&&Fnb(a);for(var e=a.Ka&&a.Na&&g.pd(d,a.Na)?a.Ka:Gnb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(Fnb(a),e=Gnb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.uf(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.IS||!g.ws(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.ws(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Vc?g.us(e,m,"1em"):g.us(e,m,"0.5em")))}a.Na=d;a.Ka=e;a.K.push(b)},Anb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},Jnb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new Inb(this);this.G=new Inb(this);this.j=[];this.clear()},Lnb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Su:a,
Zr:b,result:0};a=Knb[a];b=Knb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Ee()&&c.Zr===d;if(d)return{Su:a,Zr:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Su:a,Zr:b,result:2};return{Su:a,Zr:b,result:3}},Nnb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,Mnb(a.D,b,c,d))},Onb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.u(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Nnb(a,d.uV,d.vV,b):1===d.type&&a.B&496&&Mnb(a.G,d.uV,d.vV,b);a.j.length=0},K4=function(){this.type=0},L4=function(){this.state=this.Zr=this.Su=0},Pnb=function(){this.timestamp=this.j=0},M4=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new K4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new Pnb}},N4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Unb=function(a,b){switch(a){case 0:return Qnb[(b&127)-32];
case 1:return Rnb[b&15];case 2:return Snb[b&31];case 3:return Tnb[b&31]}return 0},O4=function(a){return a.B[a.row][a.col]},P4=function(a,b,c){2<=b&&1<a.col&&(--a.col,O4(a).j=0);
var d=O4(a);d.timestamp=a.D.time+0;d.j=Unb(b,c);32>a.col&&a.col++},Vnb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},Q4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Wnb=function(a){a.row=0<a.j?a.j:1;
a.col=1;Q4(a,0,15)},Xnb=function(a){this.C=a;
this.G=0;this.style=new K4;this.K=new M4(this.C);this.N=new M4(this.C);this.text=new M4(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Ynb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(N4(d,c),Wnb(a.B),Wnb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(N4(d,c),Q4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Znb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},$nb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},Inb=function(a){this.j=a;
this.G=0;this.C=new Xnb(this.j);this.K=new Xnb(this.j);this.B=new L4;this.D=this.C},Mnb=function(a,b,c,d){a.B.update();
b=Lnb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Su;c=b.Zr;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&P4(a,0,b),c&96&&P4(a,0,c),0!==b&&0!==c&&3===a.style.type&&N4(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Su=e,b.Zr=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(4!==b.style.type?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Vnb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));Q4(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:P4(b.j,0,32);break a;case 48:57===c?(d=b.j,O4(d).j=0,32>d.col&&d.col++):P4(b.j,1,c&15)}break;case 2:c&32&&P4(b.j,2,c&31);break;case 3:c&32&&P4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Znb(b);
break;case 33:d=b.j;1<d.col&&(--d.col,O4(d).j=0);break;case 36:d=b.j;b=O4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Ynb(b,2,d);break;case 38:Ynb(b,3,d);break;case 39:Ynb(b,4,d);break;case 40:P4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Wnb(d);$nb(b);break;case 43:$nb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:N4(a,
d)}Q4(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.col=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;N4(a,d);Vnb(a,b,b+1,a.j-1);Q4(a,a.row,1)}break;case 46:Q4(b.D,0,15);break;case 47:N4(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Znb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.col+=c&3)&&(d.col=32)}}},aob=function(){},R4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.uK.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},cob=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.ag){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=bob(l.textContent,n.textContent,p.textContent,f.textContent,h);return new R4(a,b,e,c,l,d,m)}switch(m.ag){case 9:case 10:m.oo=1;break;case 11:m.oo=2;break;case 12:m.oo=3;break;case 13:m.oo=4;break;case 14:m.oo=5}return new R4(a,b,e,c,l.textContent||"",d,m)},bob=function(a,b,c,d,e){var f=g.FC(),h=
f?g.tf("DIV"):g.tf("RUBY"),l=g.tf("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.tf("DIV"):g.tf("RP");a.textContent=b;h.appendChild(a);b=f?g.tf("DIV"):g.tf("RT");b.textContent=c;h.appendChild(b);c=e.ag;if(10===c||11===c||12===c||13===c||14===c)if(g.us(b,"text-emphasis-style","filled circle"),g.us(b,"text-emphasis-color","currentcolor"),g.us(b,"webkit-text-emphasis","filled circle"),11===e.ag||13===e.ag)g.us(b,"webkit-text-emphasis-position","under left"),g.us(b,"text-emphasis-position","under left");c=!0;if(4===e.ag||7===e.ag||12===e.ag||
14===e.ag)g.us(h,"ruby-position","over"),g.us(h,"-webkit-ruby-position","before");else if(5===e.ag||6===e.ag||11===e.ag||13===e.ag)g.us(h,"ruby-position","under"),g.us(h,"-webkit-ruby-position","after"),c=!1;e=f?g.tf("DIV"):g.tf("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.us(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.us(f,"display","none"),f=f.nextElementSibling,g.us(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.us(h.lastElementChild,"display","none"),d?(g.us(h,"padding-top","0.6em"),g.us(f,"top","0")):(g.us(h,"padding-bottom","0.6em"),g.us(f,"bottom","0")));return h},S4=function(){g.I.apply(this,arguments)},T4=function(a,b,c,d,e){g.uK.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},dob=function(a){var b="_"+U4++;
return new T4(0,0x8000000000000,0,b,a)},V4=function(a){S4.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+U4++;this.K={};this.B=this.j=null;this.G=!0},W4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},X4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},Y4=function(a,b){a=W4(a,b);
return void 0!==a?a:null},$4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Z4.test(a),a},eob=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=Y4(b,"mh");null!=a&&(c.dA=a);a=Y4(b,"ju");null!=a&&(c.textAlign=a);a=Y4(b,"pd");null!=a&&(c.Li=a);a=Y4(b,"sd");null!=a&&(c.VR=a);a=$4(b,"wfc");null!=a&&(c.windowColor=a);b=W4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},fob=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=Y4(b,"ap");null!=a&&(c.Ol=a);a=W4(b,"cc");null!=a&&(c.qs=a);a=W4(b,"ah");null!=a&&(c.ek=a);a=W4(b,"rc");null!=a&&(c.wr=a);b=W4(b,"av");null!=b&&(c.po=b);return c},gob=function(a,b,c,d){var e={};
Object.assign(e,fob(a,b));Object.assign(e,eob(a,b));d?g.pd(e,a.C)?(d=a.D,e=a.C):d="_"+U4++:d=b.getAttribute("id")||"_"+U4++;a=W4(b,"t")+c;b=W4(b,"d")||0x8000000000000;if(2===e.Li||3===e.Li)c=e.wr,e.wr=e.qs,e.qs=c;return new T4(a,b,0,d,e)},a5=function(a){S4.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},b5=function(a){a=g.xe(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},hob=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.wr=a);b=b.ccColCount;void 0!==b&&(f.qs=b);if(2===f.Li||3===f.Li)b=f.wr,f.wr=f.qs,f.qs=b;return new T4(c,d,0,e,f)},c5=function(a,b,c,d){g.aW.call(this,a);
this.videoData=b;this.audioTrack=c;this.Va=d;this.D=b.Cu},d5=function(a,b,c,d,e,f,h,l,m,n){I4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},e5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},f5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},g5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},h5=function(a,b){S4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new Jnb;this.j.B=1<<this.track},job=function(a){if("string"===typeof a)return!1;
a=new e5(a,8,0);return iob(a)},iob=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==g5(a))return!1;
a.version=f5(a);if(1<a.version)return!1;f5(a);f5(a);f5(a);return!0},i5=function(a,b,c,d,e,f,h,l,m,n){I4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ba=[];this.ma=this.W=this.Ra=0;this.Ea=NaN;this.Lb=0;this.ac=null;this.Xa=new g.ev(this.Q$,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.xV(this.element,!0),g.M(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.mv(this.element,"ytp-caption-window-rollup");g.M(this,this.Xa);g.us(this.element,"overflow","hidden")},kob=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.VR&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},lob=function(a){a.Ba=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.wr,c=0,d=0,e=a.Ba.length-1;c<b&&-1<e;){var f=a.Ba[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.W=d;b=Math;c=b.max;isNaN(a.Ea)&&((d=a.j.qs)?(e=g.tf("SPAN"),g.Ef(e,"\u2013".repeat(d)),g.us(e,Enb(a,a.j.Ve)),a.D.appendChild(e),a.Ea=e.offsetWidth,a.D.removeChild(e)):a.Ea=0);d=a.D;a.ma=c.call(b,a.Ea,a.Lb,(a.C?d.offsetHeight:d.offsetWidth)+1)},mob=function(a,b){lob(a);
var c=a.Ba.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.W-c;if(c!==a.Ra){var d=0<c&&0===a.Ra,e=c<a.Ra;b||isNaN(c)||d||!e||(g.mv(a.element,"ytp-rollup-mode"),g.fv(a.Xa));g.us(a.D,"transform",kob(a,c));a.Ra=c}lob(a)},j5=function(){S4.call(this)},nob=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new R4(b,c,d,e.id,p.nodeValue,f||0<n,g.nd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);nob(a,b,c,d,e,!0,p,q,m)}}},oob=function(a){var b=a.split(":");
a=0;b=g.u(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},pob=function(a,b,c,d){d=Object.assign({dA:0},d);
return new T4(a,b,c,"_"+U4++,d)},k5=function(a,b){g.I.call(this);
this.J=a;this.X=b;this.j=null;this.B=this.J.jz()},qob=function(a){if("string"===typeof a||job(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.zQ(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.KO(a)},sob=function(a,b,c){if("string"===typeof b||job(b))return[{trackData:b,
PR:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.rNa(d);if(a.B&&e){var f=g.iNa(e),h=g.jNa(e);e=e.j;f&&e&&a.B.XF(e,f,h)}a=g.GQ(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.KO(e),f.push({trackData:e,PR:c+1E3*h});rob(d,f,c);return f=f.filter(function(l){return!!l.trackData})},rob=function(a,b,c){var d=g.zQ(a,0,1836476516),e=9E4;
d&&(e=g.AQ(d)||9E4);d=0;for(var f=g.GQ(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.zQ(a,l.dataOffset,1953653094))&&(l=g.zQ(a,l.dataOffset,1952867444))&&(l=g.oNa(l)/e*1E3,0===h&&(d=l),b[h].PR=l-d+c||c*h*1E3)}},tob=function(a,b,c,d,e){if(!job(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new h5(e,b));return a.j.Pn(c,d)},uob=function(a,b,c){a.j||(a.j=new j5);
a=a.j.Pn(b,c);.01>Math.random()&&g.WF(Error("Deprecated subtitles format in web player: WebVTT"));return a},wob=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new a5(vob(b))),a.j.Pn(c,d)}catch(f){return g.VF(f),[]}var e=g.z2(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new V4(vob(b),a.X)),a.j.Pn(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},vob=function(a){var b=
{};
if(a=g.WS(a))b.lang=a,g.rhb.test(a)&&(b.Li=1);return b},l5=function(a){g.YV.call(this,a);
var b=this;this.J=a;this.X=this.J.U();this.videoData=this.J.getVideoData();this.ub=this.J.rb();var c;this.jb=null==(c=this.J.getVideoData(1))?void 0:g.jU(c);this.C={Ve:{}};this.G={Ve:{}};this.Ga=[];this.ra={};this.Ua={};this.W=!1;this.Wb=g.kU(this.videoData);this.Za=g.QWa(this.videoData,this.J);this.Lb=!!this.videoData.captionTracks.length;this.ac=!!this.videoData.je;this.Xa="3"===this.X.controlsType;this.j=this.N=this.Z=this.Ra=this.qb=null;this.fb=new k5(this.J,this.X);this.B=null;this.Ba=new g.hL(this);
this.K=new g.V({I:"div",S:"ytp-caption-window-container",Y:{id:"ytp-caption-window-container"}});this.ma={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.Yv("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Lv(d));this.storage=c;var e;this.Pb=!(null==(e=a.nf())||!e.OF());this.D=xob(this);this.Ea=!this.D&&this.Xa&&this.Pb&&this.Za;g.M(this,this.fb);this.D?this.Na=this.Ka=null:(this.Ka=new g.cv(this.iS,void 0,this),g.M(this,this.Ka),this.Na=new g.ev(this.Cba,2E3,this),g.M(this,
this.Na));g.M(this,this.Ba);g.KU(this.player,this.K.element,4);g.M(this,this.K);this.D||this.Ba.T(a,"resize",this.kS);(this.Db=g.uS(this.X)&&!g.WC()&&!this.J.isFullscreen()&&!this.D&&!this.Ea)&&this.Ba.T(a,"resize",this.Z9);this.Ba.T(a,"onPlaybackAudioChange",this.p9);this.Ba.T(a,g.vK("captions"),function(f){b.onCueRangeEnter(f)});
this.Ba.T(a,g.wK("captions"),function(f){b.onCueRangeExit(f)});
this.jb&&this.Ba.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
yob(this,qnb()||{});this.player.xc("onCaptionsModuleAvailable")},Bob=function(a){if(1===a.X.Db||1===a.videoData.XE||"alwayson"===g.PT(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(2===a.X.Db){if(g.FS(a.X))var c=zob(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=jnb(a.player.getAudioTrack(),g.FS(a.X));var d=g.PT(a.videoData,"yt:cc");if(void 0===Aob(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===
g.PT(a.videoData,"yt:cc")},m5=function(a,b){if(a.B&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||"FORCED_ON"===a.B},Aob=function(a){var b=void 0,c=g.pD(g.oD(),65);
if(g.FS(a.X)&&null!=c){if(null!=zob(a))return!1;b=!c}return b},Cob=function(a){var b;
a.Wb?b=new c5(a.X,a.videoData,a.getAudioTrack(),a.player):a.Za?b=new H4(a.videoData.j,a.player):a.Lb?b=new g.bW(a.X,a.videoData,a.getAudioTrack()):b=new g.fW(a.X,a.videoData.je,a.videoData.videoId,g.bTa(a.videoData),a.videoData.Nm,a.videoData.eventId);return b},o5=function(a,b){if(a.j){if(a.N&&a.N.D)return a.N.D;
g.bU(a.videoData)&&(b=!0);b||(b=a.ac?!1:a.Lb?!1:!0);b=b||Dob(a);b=g.ZV(a.j.B,b);var c=null;if(g.FS(a.X)){var d=a.J.isInline()?void 0:g.kD("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.PT(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.WS(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.WS(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.D,
e.length))for(e=g.u(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.PT(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.WS(b[f])===d[e])return b[f];d=null;a.N&&a.N.C&&(d=a.N.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||n5(a));d&&c&&g.WS(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=knb(d,c));return d}return null},n5=function(a){return a.N&&a.N.j},p5=function(a){var b=n5(a);
return!!b&&a.B===b},Eob=function(a){var b=jnb(a.player.getAudioTrack(),g.FS(a.X)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=o5(a,a.W):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&m5(a)?c=n5(a):Aob(a)||a.W||Bob(a)?c=o5(a,a.W):m5(a)&&(c=n5(a));if(a.D||a.Ea){var d=g.ZV(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.tf("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.US(f));h.setAttribute("srclang",g.WS(f));h.setAttribute("id",f.toString());a.Ea||h.setAttribute("src",a.j.Gv(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.nf();c.wC(b);c=
c.Jb();a.Pb&&a.Ba.T(c.textTracks,"change",a.Baa)}else!a.B&&c&&q5(a,c),a.player.xc("onCaptionsTrackListChanged"),a.player.xm("onApiChange")},Fob=function(a,b){var c=a.J.nf().Jb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},q5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.W=c,a.W&&(g.FS(a.X)?r5(a,!!b):s5(a,!!b)));a.B=b;m5(a)&&(a.B=n5(a));var d;Gob(a,null!=(d=a.B)?d:void 0);a.load()},Iob=function(a,b){if(b instanceof T4){var c=a.ra[b.id];
c&&c.B!==b&&(c.dispose(),delete a.ra[b.id],c=null);c||(c=Hob(a,b))&&(a.ra[b.id]=c)}else c=b.windowId,a.Ua[c]||(a.Ua[c]=[]),a.Ua[c].push(b)},Hob=function(a,b){var c=Job(a);
if(!c)return null;var d=a.B?g.WS(a.B):null;d&&g.rhb.test(d)&&(b.params.Li=1);var e=a.ub.getPlayerSize();d=e.height*a.ma.height;e=e.width*a.ma.width;"google-live"!==a.X.playerStyle||a.C.isDefault||Object.assign(b.params,a.C);switch(null!=b.params.dA?b.params.dA:1<b.j.length?1:0){case 1:return new d5(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.sL.bind(a),a.J);case 2:return new i5(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.sL.bind(a),a.J);default:return new I4(b,a.C,a.G,c.width,c.height,e,
d,a.X.experiments,a.sL.bind(a),a.J)}},yob=function(a,b,c){c=void 0===c?!1:c;
var d=t5.Ve;a.C={};Object.assign(a.C,t5);a.C.Ve={};Object.assign(a.C.Ve,d);a.G={Ve:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;Z4.test(f);e.Ve.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;Z4.test(f);e.Ve.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||t5.windowColor;Z4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ve.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Ve.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Ve;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ve.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=t5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Ve.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ve.fontFamily=f;a.loaded&&a.kS();c&&g.jD("yt-player-caption-display-settings",b,2592E3)},Lob=function(a,b,c){b&&!a.Z?(b=dob({Li:0,
lang:"en"}),a.Z=[b,new R4(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.sf(a.Z)):!b&&a.Z&&(Kob(a,a.Z),a.Z=null)},Kob=function(a,b){a.player.Zn(b);
b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.Jb(a.Ga,c.value);g.dv(a.Ka)},Gob=function(a,b){a.X.L("html5_modify_caption_vss_logging")&&(a.videoData.GB=b)},Job=function(a){var b=a.ub.getVideoContentRect(!0).height,c=a.ub.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ma.height;c*=a.ma.width;return{width:c,height:b}},s5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},r5=function(a,b){a.J.isInline()||g.jD("yt-player-sticky-caption",b,2592E3)},zob=function(a){if(!a.J.isInline())return g.kD("yt-player-sticky-caption")},xob=function(a){var b,c=!(null==(b=a.J.nf())||!b.NF());
return a.Xa&&c&&!a.Za},Dob=function(a){return a.X.L("web_deprecate_always_includes_asr_setting")&&g.FS(a.X)?!0:!!g.pD(g.oD(),66)};
g.MY.prototype.kD=g.ea(45,function(a){var b=2;this.G.has(a)?b=0:g.A2a(this,a)&&(b=1);return b});
g.d0.prototype.kD=g.ea(44,function(a){return this.hd.kD(a)});
g.MY.prototype.XF=g.ea(43,function(a,b,c){this.Ka.set(a,{zs:b,wy:c})});
g.d0.prototype.XF=g.ea(42,function(a,b,c){this.hd.XF(a,b,c)});
g.aW.prototype.LQ=g.ea(41,function(){return!1});
g.aW.prototype.zt=g.ea(40,function(){});
g.bW.prototype.zt=g.ea(39,function(a,b,c){var d=this;this.isDisposed();b=this.Gv(a,b);this.Lr();this.j=g.sC(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.fW.prototype.zt=g.ea(38,function(a,b,c){var d=this;this.isDisposed();b=this.Gv(a,b);this.Lr();this.j=g.sC(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.EV.prototype.Hy=g.ea(37,function(){for(var a=g.$e(document,"track",void 0,this.j),b=0;b<a.length;b++)g.yf(a[b])});
g.zY.prototype.Hy=g.ea(36,function(){this.mediaElement.Hy()});
g.EV.prototype.OF=g.ea(35,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.zY.prototype.OF=g.ea(34,function(){return this.mediaElement.OF()});
g.EV.prototype.NF=g.ea(33,function(){return!!this.j.textTracks});
g.zY.prototype.NF=g.ea(32,function(){return this.mediaElement.NF()});
g.EV.prototype.wC=g.ea(31,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.zY.prototype.wC=g.ea(30,function(a){this.mediaElement.wC(a)});
g.Y_.prototype.zD=g.ea(20,function(){return this.W});
g.i1.prototype.zD=g.ea(19,function(){var a;return(null==(a=g.xU(this))?void 0:a.jz())||null});
g.DU.prototype.jz=g.ea(18,function(){return this.app.zD()});
g.Y0.prototype.jz=g.ea(17,function(){var a;return(null==(a=this.Aa)?void 0:a.zD())||null});
g.nQ.prototype.aI=g.ea(3,function(a){return(a=this.cn(a))?a.j:0});
g.COa.prototype.aI=g.ea(2,function(){return 0});
var onb=/#(.)(.)(.)/,nnb=/^#(?:[0-9a-f]{3}){1,2}$/i,vnb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",
dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",
eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",
gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",
ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",
ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",
kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",
mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",
na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",
oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",
rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",
sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",
su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",
ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",
war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
G4.prototype.contains=function(a){a=g.Wb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
G4.prototype.length=function(){return this.segments.length/2};
g.w(snb,g.I);g.k=snb.prototype;g.k.xa=function(){g.I.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.vA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Qc();var b=this.j;this.j=g.Cb(this.ma.Cq(a).eb);b!==this.j&&this.W&&this.W()};
g.k.reset=function(){this.D=new G4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.iY=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Tr(a);if(a&&!this.C&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.TB(a);var b=a.eb[0],c;if(null==(c=this.player.getVideoData())?0:c.enableServerStitchedDai)if(c=this.player.jz()){var d=b.j.info.id,e=b.Pa,f=a.eb[0].D;if(this.policy.Ba){if(c=c.cI(f,e,d,3))a.D=c}else if(d=c.bz(f,e,d,3))if(c=c.kD(e),0===c)d&&(a.j=new g.gQ(d));else if(2===c){this.N.start();tnb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.yn(b.Pa)?(this.D.contains(a.eb[0].Pa)||unb(this,a),this.j=g.Cb(a.eb)):tnb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.w(H4,g.aW);g.k=H4.prototype;g.k.zt=function(a,b,c){var d=this;this.Lr();b=xnb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?ynb(this,b,"386"):ynb(this,b));if(b){var e=1E3*(b.index.aI(b.index.fn())-b.index.getStartTime(b.index.fn())),f=new g.LWa(this.X),h=function(){d.C&&d.C.reset();d.G=!0};
this.X.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new snb(f,this.J,b,function(l,m){c(l,a,m,e)},this.K||g.rL(b.info),h)}};
g.k.LQ=function(){var a=this.G;this.G=!1;return a};
g.k.Rz=function(a){var b=this.K?[new g.TS({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.TS({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?wnb(this,"386"):wnb(this);b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.$V(this.B,c.value);a()};
g.k.Lr=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Gv=function(){return""};
var Z4=/^#(?:[0-9a-f]{3}){1,2}$/i;var Cnb=["left","right","center","justify"];g.w(I4,g.V);g.k=I4.prototype;g.k.U1=function(a,b){this.Za=a;this.jb=b;var c=g.Ds(this.element,this.element.parentElement);this.qb=a-c.x;this.ub=b-c.y};
g.k.T1=function(a,b){if(a!==this.Za||b!==this.jb){g.lv(this.element,"ytp-dragging")||g.mv(this.element,"ytp-dragging");var c=g.Fs(this.element);a=a-this.qb-.02*this.playerWidth;var d=b-this.ub-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.xe(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.xe(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.xe(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.xe(c,0,1);this.B.params.Ol=b;this.B.params.po=c;this.B.params.ek=
a;this.B.params.isDefault=!1;this.j.Ol=b;this.j.po=c;this.j.ek=a;this.j.isDefault=!1;this.ra.Ol=b;this.ra.po=c;this.ra.ek=a;this.ra.isDefault=!1;this.h_()}};
g.k.S1=function(){g.ov(this.element,"ytp-dragging")};
g.k.h_=function(){this.fB(this.K)};
g.k.getType=function(){return this.type};
g.k.fB=function(a){var b=this.Db?0:Math.min(this.wW(),this.maxWidth),c=this.vW(),d=this.Db;if(d){var e=getComputedStyle(this.D.parentNode);e=J4(e.borderLeftWidth)+J4(e.borderRightWidth)+J4(e.paddingLeft)+J4(e.paddingRight)}else e=0;var f=e;e="";3===this.B.params.Li&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.us(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.sM(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=.96*this.j.ek+2;h=this.j.Ol;switch(h){case 0:case 3:case 6:(d=this.j.Ve.fontSizeIncrement)&&0<d&&2!==this.j.Li&&3!==this.j.Li&&(l=Math.max(l/(1+2*d),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=.96*this.j.po+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.us(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],"string"===typeof e.text&&(d+=e.text.split("\n").length-1,e.append||0===b||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.sM=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ga||this.K.length>b)b=0,this.Ga=!1,this.K=[],this.N=this.Na=this.Ka=null,g.wf(this.D);for(;b<a.length;b++)Hnb(this,a[b])};
g.k.wW=function(){return 0};
g.k.vW=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};Jnb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
Jnb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var Knb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];K4.prototype.set=function(a){this.type=a};
K4.prototype.get=function(){return this.type};
L4.prototype.clear=function(){this.state=0};
L4.prototype.update=function(){this.state=2===this.state?1:0};
L4.prototype.Ee=function(){return 0!==this.state};
L4.prototype.matches=function(a,b){return this.Ee()&&a===this.Su&&b===this.Zr};
Pnb.prototype.reset=function(){this.timestamp=this.j=0};
M4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
M4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
M4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Qnb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Rnb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Snb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Tnb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Xnb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Inb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};aob.prototype.D=function(){};g.w(R4,g.uK);R4.prototype.toString=function(){return g.uK.prototype.toString.call(this)};g.w(S4,g.I);S4.prototype.Pn=function(){return[]};
S4.prototype.reset=function(){};g.w(T4,g.uK);T4.prototype.toString=function(){return g.uK.prototype.toString.call(this)};
var U4=0;g.w(V4,S4);V4.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
V4.prototype.Pn=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.u(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.u(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=X4(a,"b");
null!=l&&(h.bold=l);l=X4(a,"i");null!=l&&(h.italic=l);l=X4(a,"u");null!=l&&(h.underline=l);l=Y4(a,"et");null!=l&&(h.charEdgeStyle=l);l=Y4(a,"of");null!=l&&(h.offset=l);l=$4(a,"bc");null!=l&&(h.background=l);l=$4(a,"ec");null!=l&&(h.LM=l);l=$4(a,"fc");null!=l&&(h.color=l);l=Y4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=W4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=W4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=W4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=Y4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.ag=10<l?l-1:l);a=Y4(a,"hg");null!=a&&(h.wX=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=eob(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=fob(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.u(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=gob(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!X4(m,"a");l=(W4(m,"t")||0)+l;var n=W4(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=null!=m.getAttribute("d"));for(m=0;m<r.length;m++){var t=r[m],v=void 0;0<m&&(h=!0);var x=void 0;1===t.nodeType&&(x=t);if(x&&"s"===x.tagName){if((t=(t=x.getAttribute("p"))?this.pens[t]:null)&&t.ag&&(1===t.ag?(t=r.slice(m,
m+4),4===t.length&&(v=cob(l,n,f,h,p,t,this.pens),m+=3)):v=cob(l,n,f,h,p,[x],this.pens)),!v){var B=x;v=l;x=n;t=f;var E=h,F=p,G=B.textContent?B.textContent:"",P=B.getAttribute("p");P=P?this.pens[P]:null;B=W4(B,"t")||0;v=new R4(v+B,x-B,F,t,G,E,P)}}else v=new R4(l,n,p,f,t.textContent||"",h,q);c.push(v);this.B=v}if(0<c.length)for(c[0].windowId===this.D&&(this.j=gob(this,a,b,!0),d.push(this.j)),a=g.u(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Mob=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(a5,S4);a5.prototype.reset=function(){this.B.clear()};
a5.prototype.Pn=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.u(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.LM=b5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=b5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=b5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.ag=10<h?h-1:h,f.oo=Mob.get(f.ag));e.hgHorizGroup&&(f.wX=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.u(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),void 0!==e.mhModeHint&&(f.dA=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Li=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.VR=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=b5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.u(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.ek=e.ahHorPos),void 0!==e.apPoint&&(f.Ol=e.apPoint),void 0!==e.avVerPos&&(f.po=e.avVerPos),void 0!==e.ccCols&&(f.qs=e.ccCols),void 0!==e.rcRows&&(f.wr=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.u(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=hob(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+U4++,d=hob(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;0===f&&(f=5E3);l=this.B.get(h);
var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],v=t.utf8;if(v){var x=t.tOffsetMs||0,B=null;t.pPenId&&(B=this.j.get(t.pPenId));if(2===(null!=l.params.dA?l.params.dA:1<l.j.length?1:0)&&n&&"\n"===v)continue;t=null;var E=[],F;if(F=B&&1===B.ag){F=q;var G=m;if(G+3>=F.length||!F[G+1].pPenId||!F[G+2].pPenId||!F[G+3].pPenId)F=!1;else{var P=F[G+1].pPenId;(P=this.j.get(P))&&P.ag&&2===P.ag?(P=F[G+2].pPenId,P=this.j.get(P),!P||!P.ag||3>P.ag?F=!1:
(P=F[G+3].pPenId,F=(P=this.j.get(P))&&P.ag&&2===P.ag?!0:!1)):F=!1}}if(F)x=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,G=this.j.get(q[m+2].pPenId),v=bob(v,x,F,t,G),t=new R4(e,f,p,h,v,n,B),m+=3;else{if(-1<v.indexOf("<")){var Q=void 0;E=B;F=r;G=e;P=f;var S=x,ha=p,wa=n,ua=[],ma=g.z2("<html>"+v+"</html>");if(!ma.getElementsByTagName("parsererror").length&&(null==(Q=ma.firstChild)?0:Q.childNodes.length))for(Q=g.u(ma.firstChild.childNodes),ma=Q.next();!ma.done;ma=Q.next()){ma=ma.value;var sa=void 0,da=void 0,
ba=null!=(da=null==(sa=ma.textContent)?void 0:sa.replace(/\n/g,""))?da:"";if(3!==ma.nodeType||ba&&null==ba.match(/^ *$/)){sa={};Object.assign(sa,E||F);da=void 0;switch(null==(da=ma)?void 0:da.tagName){case "b":sa.bold=!0;break;case "i":sa.italic=!0;break;case "u":sa.underline=!0}ua.push(new R4(G+S,P-S,ha,l.id,ba,wa,sa))}}E=ua}E.length||(E=[new R4(e+x,f-x,p,l.id,v,n,B||r)])}if(E.length)for(n=g.u(E),B=n.next();!B.done;B=n.next())B=B.value,d.push(B),l.j.push(B);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=
a}else b=[];return b};g.w(c5,g.aW);c5.prototype.zt=function(a,b,c){mnb(this.videoData.videoId,a.vssId,c)};
c5.prototype.Rz=function(a){if(this.audioTrack)for(var b=g.u(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.$V(this.B,c.value);a()};g.w(d5,I4);d5.prototype.sM=function(a){var b=this.B.j;I4.prototype.sM.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Nob);var e=c.j;var f=d}Hnb(this,c,d)}};
var Nob={O7:!0};g.w(e5,aob);e5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+U4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new T4(c,d-c,5,f,{textAlign:0,Ol:0,ek:2.5*b,po:5.33*a});e=new R4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.w(h5,S4);h5.prototype.Pn=function(a){a=new e5(a,a.byteLength,this.B);if(iob(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.C=g5(a)*(1E3/45):1===a.version&&(a.C=4294967296*g5(a)+g5(a)),a.G=f5(a);0<a.G;a.G--){var b=f5(a),c=f5(a),d=f5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.C,type:this.track,uV:c,vV:d,order:b.j.length}))}Onb(this.j,a);return a.B}return[]};
h5.prototype.reset=function(){this.j.clear()};g.w(i5,I4);g.k=i5.prototype;g.k.h_=function(){g.gv(this.Xa)};
g.k.Q$=function(){g.ov(this.element,"ytp-rollup-mode");this.fB(this.ac,!0)};
g.k.vW=function(){return this.C?this.ma:this.W};
g.k.wW=function(){return this.C?this.W:this.ma};
g.k.fB=function(a,b){this.ac=a;if(this.B.params.wr){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Lb=this.ma;this.W=this.ma=0;I4.prototype.fB.call(this,a);mob(this,b)}I4.prototype.fB.call(this,a)};g.w(j5,S4);
j5.prototype.Pn=function(a,b){var c=[];a=a.split(Oob);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!Pob.test(e)){var h=Qob.exec(e);if(h&&4<=h.length){var l=oob(h[1]),m=oob(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.u(n);for(var v=n.next();!v.done;v=n.next())if(v=v.value.split(":"),2===v.length){var x=v[1];switch(v[0]){case "line":v=x.split(",");v[0].endsWith("%")&&(p=v[0],h.po=Number.parseInt(p,10),2===v.length&&(q=v[1].trim()));break;case "position":v=
x.split(",");r=v[0];h.ek=Number.parseInt(r,10);2===v.length&&(t=v[1].trim());break;case "align":switch(x){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.ek=0;break;case 1:h.ek=100;break;case 2:h.ek=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Ol=q}e=e.substring(Qob.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=pob(l,m,5,t),m=new R4(l,m,5,f.id,h,!1,g.nd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Rob),1===q.length?(h=5,t=pob(l,m,h,t)):(p=h=6,t=Object.assign({qs:32},t),t=new T4(l,m,p,"_"+U4++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(v=g.z2("<html>"+n+"</html>"),v.getElementsByTagName("parsererror").length?
(x=v.createElement("span"),x.appendChild(v.createTextNode(n))):x=v.firstChild,nob(this,p,m-(p-l),h,t,0<r,x,e,c)):p=oob(n)+f}Qob.lastIndex=0}}return c};
var Pob=/^NOTE/,Oob=/(?:\r\n|\r|\n){2,}/,Qob=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Rob=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.AY.uI(j5,{Pn:"wvppt"});g.w(k5,g.I);
k5.prototype.Pn=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a){var e=d,f=sob(this,a,c),h=[];try{for(var l=g.u(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.PR;h="string"!==typeof p?h.concat(tob(this,b,p,q,e)):"WEBVTT"===p.substring(0,6)?h.concat(uob(this,p,q)):h.concat(wob(this,b,p,q))}var r=h}catch(t){g.VF(t),this.clear(),r=[]}if(0!==r.length)return r}a=qob(a);if(!a)return[];try{return"string"!==typeof a?tob(this,b,a,c,d):"WEBVTT"===a.substring(0,6)?uob(this,a,c):wob(this,b,a,
c)}catch(t){return g.VF(t),this.clear(),[]}};
k5.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
k5.prototype.reset=function(){this.j&&this.j.reset()};
k5.prototype.xa=function(){g.I.prototype.xa.call(this);this.clear()};var t5={windowColor:"#080808",windowOpacity:0,textAlign:2,Ol:7,ek:50,po:100,isDefault:!0,Ve:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(l5,g.YV);g.k=l5.prototype;g.k.xa=function(){if(this.D||this.Ea){var a=this.J.nf();a&&!a.isDisposed()&&a.Hy()}else Lob(this,!1);g.YV.prototype.xa.call(this)};
g.k.HR=function(){return this.X.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Za};
g.k.Wt=function(){if(this.Xa)return this.D||this.Ea;var a=this.getAudioTrack();if(this.HR()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=jnb(a,g.FS(this.X));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?m5(this):Aob(this)||m5(this)?!0:Bob(this)};
g.k.load=function(){var a=this;g.YV.prototype.load.call(this);this.N=this.getAudioTrack();this.j?this.B&&(this.fb.clear(),this.D?Fob(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.zt(this.B,"json3",function(b,c,d,e){if(b){var f;Gob(a,null!=(f=a.B)?f:void 0);a.j.LQ()&&(a.Ga=[],a.J.zf("captions"),g.dv(a.Ka),a.fb.reset());if(a.videoData.Nf){var h;d=(null!=(h=d)?h:0)+a.videoData.Nf}b=a.fb.Pn(b,c,d,e);if(a.jb)for(c=g.u(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.nm=a.videoData.Nf;c=!a.X.L("html5_keep_caption_data_after_seek")&&a.Za;a.player.sf(b,void 0,c);!a.W||a.Ea||p5(a)||g.ZJ(a.X)||g.wS(a.X)||g.BH(a.X)||"shortspage"===a.X.Ka||a.player.isInline()||(g.hv(a.Na),b=dob({Ol:0,ek:5,po:5,wr:2,textAlign:0,Li:0,lang:"en"}),a.Ra=[b],c=["Click "," for settings"],a.qb||(e=new g.yG(g.nwa()),g.M(a,e),a.qb=e.element),e=b.end-b.start,(f=g.US(a.B))&&a.Ra.push(new R4(b.start,e,0,b.id,f)),a.Ra.push(new R4(b.start,e,0,b.id,c[0]),new R4(b.start,e,0,b.id,a.qb,!0),new R4(b.start,
e,0,b.id,c[1],!0)),a.player.sf(a.Ra),g.fv(a.Na));!a.W||a.Ea||p5(a)||(g.FS(a.X)?r5(a,!0):s5(a,!0),a.N&&(a.N.D=a.B),a.player.Ao());a.W=!1}}),this.D||this.Ea||p5(this)||this.player.xc("captionschanged",g.VS(this.B))):(this.j=Cob(this),g.M(this,this.j),this.j.Rz(function(){Eob(a)}))};
g.k.unload=function(){this.D&&this.B?Fob(this,!1):(this.Na&&g.hv(this.Na),this.player.zf("captions"),this.Ga=[],this.j&&this.j.Lr(),this.fb.clear(),this.Z&&this.player.sf(this.Z),this.kS());g.YV.prototype.unload.call(this);this.player.Ao();this.player.xc("captionschanged",{})};
g.k.create=function(){this.Wt()&&this.load();var a;a:{var b,c,d;if(this.X.L("suggest_caption_correction_menu_item")&&this.X.L("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.u(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.J.oa("showpromotooltip",this.K.element)};
g.k.Baa=function(){for(var a=this.J.nf().Jb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.ZV(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&q5(this,b,!0)};
g.k.Wca=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ga.push(a);g.dv(this.Ka)};
g.k.onCueRangeExit=function(a){g.Jb(this.Ga,a);this.j instanceof H4&&this.j.K&&this.player.Zn([a]);g.dv(this.Ka)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.Cba=function(){Kob(this,this.Ra);this.Ra=null};
g.k.iS=function(){var a=this;if(!this.Db||!this.D){this.Ka.stop();g.dba(this.Ua);this.Ga.sort(g.wAa);var b=this.Ga;if(this.Z){var c=g.zt(b,function(f){return-1===this.Z.indexOf(f)},this);
c.length&&(b=c)}b=g.u(b);for(c=b.next();!c.done;c=b.next())Iob(this,c.value);b=g.u(Object.entries(this.ra));var d=b.next();for(c={};!d.done;c={yz:void 0,Zo:void 0},d=b.next()){var e=g.u(d.value);d=e.next().value;e=e.next().value;c.yz=d;c.Zo=e;this.Ua[c.yz]?(c.Zo.element.parentNode||(c.Zo instanceof i5||c.Zo instanceof d5||g.dd(this.ra,function(f){return function(h,l){l!==f.yz&&h.B.params.Ol===f.Zo.B.params.Ol&&h.B.params.ek===f.Zo.B.params.ek&&h.B.params.po===f.Zo.B.params.po&&(h.dispose(),delete a.ra[l]);
return l===f.yz}}(c),this),this.K.element.appendChild(c.Zo.element)),c.Zo.fB(this.Ua[c.yz])):(c.Zo.dispose(),delete this.ra[c.yz])}}};
g.k.Hba=function(){yob(this,{},!0);this.player.xc("captionssettingschanged")};
g.k.W6=function(){var a=t5.Ve;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:t5.windowColor,windowOpacity:t5.windowOpacity};var b=qnb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.E0=function(a,b){var c={};Object.assign(c,qnb());Object.assign(c,a);yob(this,c,b);this.player.xc("captionssettingschanged")};
g.k.kS=function(){!this.D&&this.loaded&&(g.ad(this.ra,function(a,b){a.dispose();delete this.ra[b]},this),this.iS())};
g.k.Eh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.xe(b,-2,4);this.E0({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&q5(this,this.B,!0);break;case "stickyLoading":void 0!==b&&this.X.K&&(g.FS(this.X)?r5(this,!!b):s5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.cb(b))break;if(g.nd(b)){q5(this,null,!0);break}a=g.ZV(this.j.B,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?knb(e,b.translationLanguage):e)}this.TK(b.position);!c||c===this.B&&this.loaded||(b=g.vMa(),a=g.WS(c),b.length&&a===b[b.length-1]||(b.push(a),g.jD("yt-player-caption-language-preferences",b)),g.FS(this.X)&&!this.J.isInline()&&g.jD("yt-player-caption-sticky-language",a,2592E3),q5(this,c,!0))}else return this.loaded&&this.B&&!p5(this)?g.VS(this.B):{};return"";case "tracklist":return this.j?g.Nr(g.ZV(this.j.B,!(!b||!b.includeAsr)),function(f){return g.VS(f)}):
[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||void 0===b||Lob(this,!!b);break;case "sampleSubtitlesCustomized":this.D||Lob(this,!!b,b);break;case "recommendedTranslationLanguages":return g.vMa();case "defaultTranslationSourceTrackIndices":return this.j?this.j.N:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.K&&a.push("stickyLoading");return a};
g.k.Fq=function(){var a=this.B;if(this.X.L("html5_modify_caption_vss_logging")){var b;return(a=null!=(b=this.videoData.GB)?b:null)?{cc:g.$Qa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.WS(a)),{cc:b}):{}};
g.k.Ica=function(){this.isSubtitlesOn()?(g.FS(this.X)?r5(this,!1):s5(this,!1),Gob(this),this.unload(),m5(this,!0)&&q5(this,n5(this),!1)):this.h0()};
g.k.h0=function(){this.isSubtitlesOn()||q5(this,p5(this)||!this.B?o5(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!p5(this)};
g.k.p9=function(){var a=p5(this);m5(this,a)?q5(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.HR()&&(this.W=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Wt()&&(a?q5(this,o5(this),!1):this.load()))};
g.k.TK=function(a){a&&(this.ma={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=100*this.ma.top+"%",this.K.element.style.left=100*this.ma.left+"%",this.K.element.style.width=100*this.ma.width+"%",this.K.element.style.height=100*this.ma.height+"%",this.K.element.style.position="absolute",a=Job(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){"newdata"===a&&(this.videoData=b,this.loaded&&this.unload(),this.W=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.xc("captionschanged",{})),this.Wt()&&this.load())};
g.k.getAudioTrack=function(){return this.jb&&2===this.player.getPresentingPlayerType()?this.videoData.wl:this.player.getAudioTrack()};
g.k.Z9=function(){var a=this.J.nf();a&&!a.isDisposed()&&a.Hy();this.J.isFullscreen()?(this.D=this.Xa=!0,this.loaded&&Eob(this)):(this.Xa="3"===this.X.controlsType,this.D=xob(this));q5(this,this.B)};
g.k.sL=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.ib("innertubeCommand",d)};
g.AY.uI(l5,{iS:"smucd"});g.XV("captions",l5);})(_yt_player);
